kind: Service
apiVersion: v1
metadata:
  name: observai-ui
  namespace: observai-main
  labels:
    app: observai-ui
    app.kubernetes.io/component: observai-ui
    app.kubernetes.io/instance: observai-ui
    app.kubernetes.io/name: observai-ui
    app.kubernetes.io/part-of: observai
    app.openshift.io/runtime-version: latest
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: observai-ui
    deployment: observai-ui
