apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: custom-scc
  namespace: datamesh-workspace
rules:
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - anyuid
    - privileged
    resources:
    - securitycontextconstraints
    verbs:
    - use