kind: Service
apiVersion: v1
metadata:
  name: vendor-srv-3
  namespace: observai-main
  labels:
    app: vendor-srv-3
    app.kubernetes.io/component: vendor-srv-3
    app.kubernetes.io/instance: vendor-srv-3
    app.kubernetes.io/name: vendor-srv-3
    app.kubernetes.io/part-of: testcase-3
    app.openshift.io/runtime-version: latest
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: vendor-srv-3
    deployment: vendor-srv-3
status:
  loadBalancer: {}

# --- 

# kind: Service
# apiVersion: v1
# metadata:
#   name: order-srv-1
#   namespace: observai-main
#   labels:
#     app: order-srv-1
#     app.kubernetes.io/component: order-srv-1
#     app.kubernetes.io/instance: order-srv-1
#     app.kubernetes.io/name: order-srv-1
#     app.kubernetes.io/part-of: testcase-3
#     app.openshift.io/runtime-version: latest
# spec:
#   ipFamilies:
#     - IPv4
#   ports:
#     - name: 5089-tcp
#       protocol: TCP
#       port: 5089
#       targetPort: 5089
#   internalTrafficPolicy: Cluster
#   type: ClusterIP
#   ipFamilyPolicy: SingleStack
#   sessionAffinity: None
#   selector:
#     app: order-srv-1
#     deployment: order-srv-1
# status:
#   loadBalancer: {}

# --- 