kind: Deployment
apiVersion: apps/v1
metadata:
  name: observai-persistance-api
  namespace: observai-main
  labels:
    app: observai-persistance-api
    app.kubernetes.io/component: observai-persistance-api
    app.kubernetes.io/instance: observai-persistance-api
    app.kubernetes.io/name: observai-persistance-api
    app.kubernetes.io/part-of: observai
    app.openshift.io/runtime: quarkus
    app.openshift.io/runtime-namespace: observai-main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observai-persistance-api
  template:
    metadata:
      labels:
        app: observai-persistance-api
        deployment: observai-persistance-api
    spec:
      imagePullSecrets:
        - name: sharanya-quay-secret
      containers:
        - name: observai-persistance-api
          image: >-
            quay.io/zagaos/observai-persistance-api:latest
          ports:
            - containerPort: 8082
              protocol: TCP
          env:
            - name: APP_HOST
              valueFrom:
                configMapKeyRef:
                  name: observai-backend-config
                  key: APP_HOST
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: observai-backend-config
                  key: APP_PORT
            - name: KEPLER_BOOTSTRAP_URL
              valueFrom:
                configMapKeyRef:
                  name: observai-backend-config
                  key: KEPLER_BOOTSTRAP_URL
            - name: KEPLER_OFFSET_RESET
              valueFrom:
                configMapKeyRef:
                  name: observai-backend-config
                  key: KEPLER_OFFSET_RESET
            - name: KEPLER_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: observai-backend-config
                  key: KEPLER_TOPIC
            - name: LOG_BOOTSTRAP_URL
              valueFrom:
                configMapKeyRef:
                  name: observai-backend-config
                  key: LOG_BOOTSTRAP_URL
            - name: LOG_OFFSET_RESET
              valueFrom:
                configMapKeyRef:
                  name: observai-backend-config
                  key: LOG_OFFSET_RESET
            - name: LOG_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: observai-backend-config
                  key: LOG_TOPIC
            - name: METRIC_BOOTSTRAP_URL
              valueFrom:
                configMapKeyRef:
                  name: observai-backend-config
                  key: METRIC_BOOTSTRAP_URL
            - name: METRIC_OFFSET_RESET
              valueFrom:
                configMapKeyRef:
                  name: observai-backend-config
                  key: METRIC_OFFSET_RESET
            - name: METRIC_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: observai-backend-config
                  key: METRIC_TOPIC
            - name: TRACE_BOOTSTRAP_URL
              valueFrom:
                configMapKeyRef:
                  name: observai-backend-config
                  key: TRACE_BOOTSTRAP_URL
            - name: TRACE_OFFSET_RESET
              valueFrom:
                configMapKeyRef:
                  name: observai-backend-config
                  key: TRACE_OFFSET_RESET
            - name: TRACE_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: observai-backend-config
                  key: TRACE_TOPIC
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: observai-backend-config
                  key: MONGODB_URL
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600