apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{.Values.orderservice.name}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{ .Values.orderservice.name }}
  to:
    kind: Service
    name: {{.Values.orderservice.name}}
  port: 
    targetPort: {{.Values.orderservice.service.ports.targetPort}}
  # tls:
  #   termination: edge
  #   insecureEdgeTerminationPolicy: Redirect     

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{.Values.vendorservice.name}}
  namespace: {{.Values.namespace}}
spec:
  selector:
    app: {{ .Values.vendorservice.name }}
  to:
    kind: Service
    name: {{.Values.vendorservice.name}}
  port: 
    targetPort: {{.Values.vendorservice.service.ports.targetPort}}
  # tls:
  #   termination: edge
  #   insecureEdgeTerminationPolicy: Redirect     

