namespace: observai-main
imagesecret: sharanya-quay-secrets
vendorservice:
  name: vendor-srv-3
  icon: quarkus
  replicaCount: 1
  image:
    repository: quay.io/zagaos/vendorproject_testcase_3
    tag: latest
  service:
    type: ClusterIP
    ports:
      port: 8080
      targetPort: 8080
  config:
    POSTGRES_URL: "jdbc:postgresql://zaga-postgres.postgresql-space.svc.cluster.local:5432/observability-demo-tables"
    POSTGRES_USER: "observability-demo-user"
    POSTGRES_PASSWORD: "observability123"
    APP_APIURL: "http://192.168.1.210:8003/orders/getOrders"


