apiVersion: apps/v1
kind: Deployment
metadata:
 name: zaga-hive
 namespace: datamesh-space
spec:
 replicas: 1
 selector:
  matchLabels: 
    app: zaga-hive
 template:
   metadata:
    labels:
      app: zaga-hive
   spec:
     securityContext:
      runAsUser: 0
     imagePullSecrets:
     - name: sharanya-quay-secrets
     serviceAccountName: hive-metastore
     containers:
     - name: hive-metastore 
       image: quay.io/zagaos/hive-metastore
       env:
       - name: HIVE_DB_EXTERNAL
         value: "true"
       - name: DATABASE_HOST
         value: "zaga-postgres.datamesh-space.svc.cluster.local"
       - name: DATABASE_PORT
         value: "5432"
       - name: DATABASE_DB
         value: "zagahivedb"
       - name: DATABASE_USER
         value: "zagahiveuser"
       - name: DATABASE_PASSWORD
         value: "zagahive123"
       - name: AWS_ACCESS_KEY_ID
         value: "zagaaccesskey"
       - name: AWS_SECRET_ACCESS_KEY
         value: "zagasecretkey"
       - name: S3_ENDPOINT_URL
         value: "http://zaga-minio-hl.datamesh-space.svc.cluster.local:9000"
       - name: S3_BUCKET
         value: "hivebucket"
       - name: S3_PREFIX
         value: "persons"
       ports:
       - name: tcp
         containerPort: 9083
         protocol: TCP
