apiVersion: v1
kind: Service
metadata:
  name: zaga-hive
  namespace: datamesh-observability
spec:
  type: ClusterIP
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
      protocol: TCP
  selector:
    app: zaga-hive