kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: order-srv-2
  namespace: observai-main
  labels:
    app: order-srv-2
    app.kubernetes.io/component: order-srv-2
    app.kubernetes.io/instance: order-srv-2
    app.kubernetes.io/name: order-srv-2
    app.kubernetes.io/part-of: testcase-2
    app.openshift.io/runtime-version: latest
spec:
  # host: order-srv-2-observai-main.apps.zagaopenshift.zagaopensource.com
  to:
    kind: Service
    name: order-srv-2
    weight: 100
  port:
    targetPort: 5089-tcp
  wildcardPolicy: None

--- 

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: vendor-srv-2
  namespace: observai-main
  labels:
    app: vendor-srv-2
    app.kubernetes.io/component: vendor-srv-2
    app.kubernetes.io/instance: vendor-srv-2
    app.kubernetes.io/name: vendor-srv-2
    app.kubernetes.io/part-of: testcase-2
    app.openshift.io/runtime-version: latest
spec:
  # host: vendor-srv-2-observai-main.apps.zagaopenshift.zagaopensource.com
  to:
    kind: Service
    name: vendor-srv-2
    weight: 100
  port:
    targetPort: 8080-tcp
  wildcardPolicy: None