apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.kafkaservice.name }}-config
  namespace: {{.Values.namespace}}
data:
  MONGODB_URL: "{{.Values.kafkaservice.config.MONGODB_URL}}"
  PRODUCT_BOOTSTRAP_URL: "{{.Values.kafkaservice.config.PRODUCT_BOOTSTRAP_URL}}"
  PRODUCT_TOPIC: "{{.Values.kafkaservice.config.PRODUCT_TOPIC}}"

---

