apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  generation: 3
  name: custom-datamesh-scc
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
allowedUnsafeSysctls:
- '*'
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
- '*'
supplementalGroups:
  type: RunAsAny
users:
# addd namespace as per your wish
- datamesh-observability
- system:serviceaccount:datamesh-observability:zaga-minio-sa
- system:serviceaccount:datamesh-observability:trino-dafault
- system:serviceaccount:datamesh-observability:superset-serviceaccount
groups:
- system:cluster-admins
- system:nodes
- system:masters
volumes:
- '*'
 