kind: Service
apiVersion: v1
metadata:
  name: observai-query-api
  namespace: observai-main
  labels:
    app: observai-query-api
    app.kubernetes.io/component: observai-query-api
    app.kubernetes.io/instance: observai-query-api
    app.kubernetes.io/name: observai-query-api
    app.kubernetes.io/part-of: observai-insecure
    app.openshift.io/runtime-version: latest
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8081-tcp
      protocol: TCP
      port: 8081
      targetPort: 8081
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: observai-query-api
    deployment: observai-query-api